### ISSUE TITLE
Add all() method to SearchIterator

### ISSUE THREAD

**Issue by xuru** [numberoverzero/bloop#102]
Coming from an SQLAlchemy or other ORMs that are out there, having an `all()` method on the query feels natural and adds symmetry to `.one()` and `.first()`. 

> I think that implementing `.all()` is going to be:
```
def all(self):
    self.reset()
    return list(self)
```
> my concern here is people assuming they need to call a method on the result of `engine.query(...)` instead of just iterating that thing; in a lot of cases you don't need the entire list, and can stop early.  If everyone reaches for `all`, they'll be hurting performance quite a bit.

> But, it does add pleasing symmetry to `.first` and `.one`, so I'd consider it worth an issue to add `.all()` back to SearchIterator; docs just need to be clear that you don't *need* to use that method to get results.

**Comment by numberoverzero** [comment]
* [ ] SearchIterator exposes `all()` method documented above
* [ ] Docs:
  * [ ] `SearchIterator.all` docstring
  * [ ] `api/internal.rst`
  * [ ] `api/public.rst`
  * [ ] `meta/changelog.rst`
  * [ ] `user/engine.rst`
  * [ ] `CHANGELOG.rst`

Unit tests can probably clone off of the existing tests for either `.one` or `.first`, and should make sure that the mocked `SessionWrapper` functions are called a second time (specifically to ensure that the query is executed again, and a cached copy isn't stored somewhere).  They should also ensure the query/scan is exhausted after the first and second `.all` calls.

**Comment by numberoverzero** [comment]
Hey @xuru,

With the release of 2.2 (#123) I believe this can be closed.
Here are the new and updated docs:

* [User Guide](https://bloop.readthedocs.io/en/latest/user/engine.html#all)
* [Public API - QueryIterator](https://bloop.readthedocs.io/en/latest/api/public.html#bloop.search.QueryIterator.all)
* [Public API - ScanIterator](https://bloop.readthedocs.io/en/latest/api/public.html#bloop.search.ScanIterator.all)
* [Internal API - SearchIterator](https://bloop.readthedocs.io/en/latest/api/internal.html#bloop.search.SearchIterator.all)
* [Internal API - SearchModelIterator](https://bloop.readthedocs.io/en/latest/api/internal.html#bloop.search.SearchModelIterator.all)

If you think anything's missing or could be improved feel free to comment or re-open.  Thanks for your contributions!
