### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by DaddyGrimmlin** [numberoverzero/bloop#109]
I am getting a syntax error now that I am using 2.0.0 in models.py Line 47

`.env/lib/python3.5/site-packages/bloop-2.0.0-py3.5.egg/bloop/models.py", line 47
    abstract: bool
            ^
SyntaxError: invalid syntax`

Any ideas?

**Comment by numberoverzero** [comment]
Thanks for opening an issue, and sorry you're running into this problem.  This is because bloop 2.0 uses new syntax from python 3.6+ ([PEP-526](https://www.python.org/dev/peps/pep-0526/)).

**Comment by numberoverzero** [comment]
Closing this out since it's likely a python version issue.  Feel free to re-open with additional debugging info.
