### ISSUE TITLE
Bloop silently ignoring records from a stream

### ISSUE THREAD

**Issue by andrewsi** [numberoverzero/bloop#111]
Firstly, apologies if this is a little vague; please let me know if I've missed something important.

I've been using Bloop to connect to an existing DynamoDB stream. It's working very well, but I've noticed that there are occasionally records missing. I can see them on DynamoDB, and running my code on DEBUG shows that they're being retrieved, but they're not being processed - it looks like they're getting discarded before being passed to the processing loop.

After poking around, I think I've narrowed down what the issue is, but have no idea how to fix it (or, to be fair, if this is what the problem actually is.)

I've been using the AWS command line tool to see what's going on. I get a shard iterator, and iterate through the shard. The first call returns records, as well as a NextShardIterator item; when I use that to get the next set of records, I get a result that includes my missing records, but no NextShardIterator.

That tallies with what I'm seeing in the debug output - the first call shows the initial batch of records, which are then processed, and the second call shows the final batch, but none of them are processed - the code moves on to the next shard, and those records never appear.

Of course, there's also a good chance that I'm doing something wrong, too.... 

Please let me know if there's any more information I can provide to try and get this resolved.

**Comment by numberoverzero** [comment]
Thanks for opening an issue, and for the detailed research.  Sorry you're encountering this; if it's a bug in bloop it's a serious one.

The only time that GetRecords should omit a NextShardIterator is when you've reached the end of a closed shard.  So this is a stream that's been open for at least 4 hours, and bloop is potentially dropping the last set of records from the closed shard, or the first set of records from the subsequent shard.

For ease of discussion, I'm going to contrive a set of shards and GetRecords responses that we can point at:

```
(within a single stream)

GetShardIterator Shard00, TRIM HORIZON)
    --> IterId00

GetRecords IterId00
    --> Records (0, 1, 2) NSI IterId10

GetRecords IterId10
    --> Records (3, 4, 5) NSI IterId20

GetRecords IterId20
    --> Records (6, 7, 8) // No NSI, closed shard

GetShardIterator Shard100, TRIM HORIZON)
    --> IterId100

GetRecords IterId100
    --> Records (90, 100, 110) NSI IterId200
```

In your case, bloop is retrieving records 1-5 inclusive, omitting 6-8 inclusive, and retrieving 90-110 inclusive?

That sounds like the shard tracking is purging the buffered records when it removes the shard, but I'd still expect the first record (in the example, record 6) to be returned.  So something like:

```
user request for next record
buffer empty
  --> GetRecords returns records 6-8 and no NSI
    --> records 6-8 inserted in buffer
    --> no NSI, shard transition logic begins
      --> purge buffered records for shard being removed  // Records 6-8 lost here
```

**Comment by numberoverzero** [comment]
Here's the code that polls active shards when there are no buffered records; it indeed pushes the records before cleaning up closed shards: [`bloop.stream.coordinator.Coordinator.advance_shards`](https://github.com/numberoverzero/bloop/blob/81d0984798749a674178f342e5cf96ae80b48f8b/bloop/stream/coordinator.py#L67-L84)

At the end of that function is a call to `Coordinator._handle_exhausted`, which finds the next shards for each closing shard, then calls `Coordinator.remove_shard` on each closed shard.

* [`bloop.stream.Coordinator._handle_exhausted`](https://github.com/numberoverzero/bloop/blob/81d0984798749a674178f342e5cf96ae80b48f8b/bloop/stream/coordinator.py#L96-L104)
* [`bloop.stream.Coordinator.remove_shard`](https://github.com/numberoverzero/bloop/blob/81d0984798749a674178f342e5cf96ae80b48f8b/bloop/stream/coordinator.py#L96-L104)

The docstring for `Coordinator.remove_shard` accurately captures that it in fact, `Drops all buffered records from the Shard`. 👎

From the quick review, this is very likely a bug.  Next question, why didn't unit tests catch it?  It could be a one-off that I missed, or the specific test is wrong, or it could be a more systemic issue over all of the stream unit tests.  That would be very bad.

**Comment by andrewsi** [comment]
Your test case is exactly what I can see happening.

There's a first batch of records, which are all processed; a second batch, which are not; and then additional ones that are processed. 

If it'd help track the issue down, I do have the DEBUG output from when I was testing it, as well as the contents of the shard involved?

**Comment by numberoverzero** [comment]
I think I've got enough to go dig through unit tests, and I'm fairly confident from the code links above that this is the shard rotation clearing out the buffer before the records are served.  It might also impact the token logic (which would point to the new shard even though the closed shard hasn't cleared the buffer).

Unfortunately I won't be able to investigate for a few hours but I'll try to come back to this today to at least identify the missing/failed unit test.  [Tests are here](https://github.com/numberoverzero/bloop/blob/master/tests/unit/test_stream/test_coordinator.py) if you want to take a look but they may not be very approachable.  It's been a while since I touched that code.

**Comment by numberoverzero** [comment]
https://github.com/numberoverzero/bloop/tree/fix/111

If it's not too much trouble can you give this branch a try and report back?  This should take care of missing records and correct the token issue.  Thanks!

**Comment by andrewsi** [comment]
Thank you very much - I'll give it a try. Thanks to shards expiring, I can no longer test it out against the misbehaving shard - I can at least see if the problem crops up again, however.

I've also just run into another issue. One of the stream consumers stopped working overnight; from the log output, it seems that as part of a describe_stream call, it was passed an empty list of shards.

That's definitely incorrect (that shard list was populated when it was started, and it's populated when I check now) and I can't see anything in the documentation about what the root cause might be; do you have any ideas?

**Comment by numberoverzero** [comment]
Did some manual tests, so I'm going to merge #112 tonight.  That should resolve the issue, and you can pick up `bloop==2.0.1` in a bit.
