### ISSUE TITLE
Chaining multiple filters

### ISSUE THREAD

**Issue by trondhindenes** [numberoverzero/bloop#121]
I'm having problems understanding the best way to chain multiple `AND` filters together. I know I can do something like:
```
        results = self.engine.scan(
            ProvisioningJob,
            filter=bloop.conditions.AndCondition(
                ProvisioningJob.environment == environment,
                ProvisioningJob.environment_id == environment_id))
```
However, it seems a bit cumbersome and I'm suspecting there's an easier way - but I can't find it in the documentation (all examples are using a single filter condition)

**Comment by numberoverzero** [comment]
Thanks for opening an issue; this needs to be called out more clearly in the documentation.  The `&` operator is overloaded for `AND` while the `|` operator is overloaded for `OR`.  There's also `~` for `NOT` but much less frequently used.

```
results = self.engine.scan(
    ProvisioningJob,
    filter=(
        (ProvisioningJob.environment == environment) &
        (ProvisioningJob.environment_id == environment_id)
    ))
```

**Comment by numberoverzero** [comment]
There's a vastly insufficient mention in [this section](https://bloop.readthedocs.io/en/latest/user/conditions.html#built-in-conditions) but the chaining and complex conditions really deserves its own section.  For example, if you're dynamically constructing queries by column name, I've found the `operators` module very helpful:

```
import bloop
import operator

from models import Article, Editor, Paper, engine

ops = {
    ">": operator.gt,
    "=": operator.eq,
    ...
}
# this lookup could be done dynamically by iterating subclasses of BaseModel
by_name = {
    "articles": Article,
    "editors": Editor,
    "papers": Paper,
}


def build_query(request: str) -> bloop.QueryIterator:
    # TODO impl the explode method
    # model_name is pulled from the path
    # params comes out a list of (key, op, value) tuples
    # [("publishDate", ">", "20180309"), (...), ...]
    mname, params = explode(request)
    
    model = by_name[mname]
    condition = bloop.Condition()
    for (cname, op_str, value) in params:
        col = model.Meta.columns_by_name[cname]
        condition &= ops[op_str](col, value)

    return engine.query(model, filter_condition=condition)


q = build("/articles?editor=Nancy&publishDate>20180309&isDraft=false")
for article in q:
    print(article.id)
```

**Comment by numberoverzero** [comment]
Hey @trondhindenes,

With the release of 2.2 (#123) I believe this can be closed.
Here are the new and updated docs:

* [User Guide - Conditions - Chained Conditions](https://bloop.readthedocs.io/en/latest/user/conditions.html#chained-conditions-and-or)

If you think anything's missing or could be improved feel free to comment or re-open.  Thanks for your feedback!

**Comment by trondhindenes** [comment]
that's awesome, thanks!
