### ISSUE TITLE
Support Trasactions

### ISSUE THREAD

**Issue by numberoverzero** [numberoverzero/bloop#127]
https://forums.aws.amazon.com/ann.jspa?annID=6392
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transactions.html
* [`TransactGetItems`](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactGetItems.html)
* [`TransactWriteItems`](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html)

This is a super exciting capability, and allows bloop to support multi-table atomic transactions (#120) without the ~8x throughput cost of the previous library.

This warrants a new section in the User Guide before "Streams".  Like the "Conditions" page, this section should provide both bloop-specific syntax as well as a high-level overview of when to use this feature.  Multiple links to the developer guide as well as the raw APIs above should be used.  There also needs to be a new heading under the "Using the Engine" page for `engine.transaction` below.

## usage

```
with engine.transaction() as tx:
    tx.save(user, tweet)
    tx.delete(expired_credential)
    tx.check(metadata, Metadata.suspended.is_(False))
```

----

**EDIT** leaving the open questions below in case there's an opportunity for future enhancements, but for now the decisions were: no shortcut from save/delete; split public tx classes; no top-level atomic; no update on conflict; use idempotency tokens on writes; dump objects in `prepare()` method.

---

#### expose shortcut in save/delete

Should `engine.delete` and `engine.save` expose a `tx: bool=False` optional argument so that a multi-object save can be done in a transaction in one line?  For example, compare:

```
engine.save(user, tweet, tx=True)

with engine.transaction() as tx:
    tx.save(user, tweet)
```

This could be accomplished in one line if the new `Transaction` class exposes a `.commit` operation and the tx methods are chainable:

```
engine.transaction().save(user, tweet).commit()

# or with an alias:
engine.tx().save(user, tweet).commit()
```

#### single `Transaction` class or split on mode

There will be a `mode=` option to `engine.transaction` that takes either `"r"` or `"w"` like `open`.  This can either be passed to a single `Transaction` class that disables the incorrect methods for that mode, or it can return a different type of object for each call.

#### expose atomic conditions

Transactions can have top-level conditions attached to different tables, or conditions attached to individual objects.  The syntax example shows:

```
"TransactItems": [ 
      { 
         "ConditionCheck": { 
            "ConditionExpression": "string",
            "ExpressionAttributeNames": { 
               "string" : "string" 
            },
            "ExpressionAttributeValues": { 
               "string" : { 
                  "B": blob,
                  "BOOL": boolean,
                  ...
               }
            },
            ...
         },
         "Delete": { 
            "ConditionExpression": "string",
            "ExpressionAttributeNames": { 
               "string" : "string" 
            },
            "ExpressionAttributeValues": { 
               "string" : { 
                  "B": blob,
                  "BOOL": boolean,
                  ...
               }
            },
            ...
         },
         ...
      },
...
]
```

Since the `update` and `delete` shapes match the existing `UpdateItem` and `DeleteItem` operations the renderer doesn't need to change, and we can still provide an `atomic: bool=False` option on `tx.save()` and `tx.delete()`.  These conditions would be applied to the individual update/delete objects, while a new method `tx.require(obj, condition)` (name tbd) would exist to support transaction conditions on objects outside the transaction.

If the new Transaction class supports `atomic=` on operations, it may be worth exposing an option in the constructor:

```
with engine.transaction(atomic=True) as tx:
    tx.save(user, condition=something)
    tx.save(tweet, condition=another)
```

Where the value of the constructor's `atomic` is used when not specified in the tx operation's call.

#### expose option to update on conflict

There is a request key `"ReturnValuesOnConditionCheckFailure"` which exists on each transaction item in the list, with the description "a field indicating whether or not to retrieve the item's attributes if the condition is not met".  Combined with the following definition of when a transaction is rejected:

> DynamoDB rejects the entire TransactGetItems request if any of the following is true:
> * A conflicting operation is in the process of updating an item to be read.
> * There is insufficient provisioned capacity for the transaction to be completed.
> * There is a user error, such as an invalid data format.

it seems that the new values should be exposed somewhere in the response but the definition for the `"TransactionCanceledException"` response does not indicate that it has fields.

This would be especially useful in the case where you immediately query dynamo after a tx fails.  Like the `atomic` option above, this might be best exposed as an option on each operation as well as in the constructor.

#### support ClientRequestToken

There's an optional [`ClientRequestToken`](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html#DDB-TransactWriteItems-request-ClientRequestToken) parameter that could be used when constructing the transaction.  This would allow idempotent retries on non-conflict error codes for up to 10 minutes (minus clock skew) so that a user could call `tx.commit()` in a retry policy.

Going by the same parameter name in Cloudformation's [`StackEvent`](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_StackEvent.html) the restriction is `[a-zA-Z0-9]{1,128}`.  For simplicity this could use `uuid`:

```
>>> import uuid; str(uuid.uuid4()).replace("-", "")
>>> 'd4b87b78560b46779ebf2829295d82a8'
```

#### dump objects timing

Object dumping can happen either:

1. when added to the tx with `tx.save`, `tx.delete`, or `tx.requre`
2. the **first** call to `tx.commit()`
3. every time `tx.commit()` is called

The first option provides the fasted failure message, at the line where the invalid object was added.  However, it also means that defaults and time-based values might serialize a long time before subsequent items in the tx are added.  Consider two objects with a `createdOn` field that uses a default value of `lambda: datetime.now()` and there is a long pause between adding them to the tx.

The second option adds an extra attr to the class (`_dumped_items` or something) and moves the error away from the save/delete/require that caused it.  However, it makes default functions easier to reason about and probably aligns better with what users expect from tx semantics.  There's no work occurring when preparing the tx, only when commit is called.

The third option is like the second but without the cache has different retry semantics.  I think this is just worse; for custom types eg. reference types that cause cascading loads/deletes it would be fairly heavy for every tx.commit to re-run those.

**Comment by numberoverzero** [comment]
remaining doc work: version bump, changelogs, and user/transactions.rst

**Comment by Surgo** [comment]
@numberoverzero Thank you so much 🎉 I'll try it :)
