### ISSUE TITLE
Iterator doesn't identify exhausted state when last evaluated key is last record of table

### ISSUE THREAD

**Issue by platta** [numberoverzero/bloop#134]
Every time an iterator issues a request against the DynamoDB API, it checks the result for the LastEvaluatedKey property. The assumption is that if that property is populated there are more records to retrieve. If the LastEvaluatedKey is the last record of the table (likely a rare case with real world data), calling the DynamoDB API again with that key as the ExclusiveStartKey will result in zero records returned.

With the current implementation, upon retrieving the actual last record from the table, the exhausted property still returns `False`. When attempting to access the next item, DynamoDB is called but returns zero records, and control falls through to the end of the `__next__()` method, raising a StopIteration error.

One solution is to have the iterator call DynamoDB when there is _one_ item left in the local buffer. That way we can guarantee we'll be able to determine if the table is exhausted before returning what might be the last item. To achieve this you could make a change around 513 in `search.py` 

Change

```
while (not self._exhausted) and len(self.buffer) == 0:
```
To

```
while (not self._exhausted) and len(self.buffer) <= 1:
```

Here is a program to reproduce the issue:
```
from bloop import (BaseModel, String, Integer, Column, DateTime, Number,
                   Engine, GlobalSecondaryIndex, LocalSecondaryIndex)


class Account(BaseModel):
    name = Column(String, hash_key=True)
    number = Column(Integer, range_key=True)
    created_on = Column(DateTime)
    balance = Column(Number)
    level = Column(Integer)

    by_level = GlobalSecondaryIndex(
        projection="all", hash_key=level)

    by_balance = LocalSecondaryIndex(
        projection=["created_on"], range_key="balance")


def make_accounts(engine):
    for x in range(0, 10):
        y = Account(name='Account{0}'.format(x), number=x)
        engine.save(y)


def main():
    engine = Engine()
    engine.bind(Account)
    make_accounts(engine)

    q = engine.scan(Account)
    q.request['Limit'] = 5
    while not q.exhausted:
        next(q)
        print(q.request['ExclusiveStartKey'])


if __name__ == '__main__':
    main()
```

**Comment by platta** [comment]
Found this while testing for #132. Although the fix I suggested is a simple one-line change, I think there will be more consideration required once continuation tokens are in the mix. Planning to come back to this after we finish hashing out the details of #132.

**Comment by numberoverzero** [comment]
Thanks for opening this issue.  I don't think this is exactly a bug, but it can be a little more user friendly with the change you suggested.  It might cause misses at the end of the query for very slow iteration and high write rates, but most searches are eventually consistent anyway.

A slight clarification about this line:
> The assumption is that if that property is populated there are more records to retrieve.

AWS services are designed to have very consistent request patterns (request duration, resources used, network hops) and so LastEvaluatedKey doesn't indicate there are necessarily more records, but rather that this request stopped looking for more and you should call again to continue evaluation.  The result looks odd when the work size exactly equals the remaining items, because then AWS must return an empty page.

**Comment by platta** [comment]
You know, I'm still learning some of the finer points of Python as a language. A little googling and now I understand that the `StopIteration` error is the standard way of doing things. I didn't realize that.

In that case I definitely agree.
