### ISSUE TITLE
Document how to use composite keys

### ISSUE THREAD

**Issue by funkybob** [numberoverzero/bloop#46]
I may be a bit to noob to see this, but I can't see a clear example of defining a composite key using bloop.

**Comment by numberoverzero** [comment]
Thanks for the report!

It looks like there was a change in terminology at some point; previously a table required a `hash` key and could optionally have a `range` key, but now that's changed to `partition` key and `sort` key, where using both is considered a `composite` key.

---

To answer your question, a composite key would be declared as such:

```python
from bloop import new_base, Column, Integer, String

class Thread(new_base()):
    # A composite key is made up of a hash and range key
    # (or, in current Dynamo vocabulary, a partition and sort key)
    forum_id = Column(Integer, hash_key=True)
    thread_id = Column(Integer, range_key=True)

    # Here are some other fields, that are not part of the key
    author_id = Column(Integer)
    title = Column(String)
```

---

As bloop approaches 1.0.0 I'll need to consider picking up the new names; my gut check says yes, but that means a slightly longer on-boarding time for a decent number of users.

**Comment by funkybob** [comment]
Excellent answer, thanks!

**Comment by numberoverzero** [comment]
Here's another issue that references it: guregu/dynamo#15

I'll see if I can find an official announcement and then add a section to the docs on key names.  For now I'm going to continue on with `hash` and `range` until the large refactorings are done, and when it comes time to plan the 1.0.0 (hopefully in a month or two) I'll revisit this.

Thanks again for the report, this will probably be a common source of confusion over the next few years.

**Comment by numberoverzero** [comment]
And here's the release note that quietly changed everything: https://aws.amazon.com/releasenotes/Amazon-DynamoDB/9068906752066271

No sign that the APIs will change to reflect this, which isn't a surprise.  Maybe that's next year...

**Comment by funkybob** [comment]
This from the same company whose ELB team couldn't fathom why you might want to know _why_ they rejected your response.... nah, doesn't surprise me in the least :)
